/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import clases.*;
import javax.swing.JOptionPane;
import BaseDdatos.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author diego
 */
public class FormularioTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form FormularioTarjeta
     */
    Usuario us=null;
    public FormularioTarjeta(Usuario us) {
        initComponents();
        this.us=us;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wa4 = new javax.swing.JLabel();
        wa1 = new javax.swing.JLabel();
        wa = new javax.swing.JLabel();
        numeroTarjeta = new javax.swing.JTextField();
        Mes = new javax.swing.JTextField();
        wa3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        Año = new javax.swing.JTextField();
        wa2 = new javax.swing.JLabel();
        numeroTarjeta1 = new javax.swing.JTextField();
        numeroTarjeta2 = new javax.swing.JTextField();
        numeroTarjeta3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        wa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N

        wa1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        wa1.setText("Fecha exp:");

        wa.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        wa.setText("Número de tarjeta:");

        numeroTarjeta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numeroTarjeta.setText("****");
        numeroTarjeta.setToolTipText("");
        numeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaActionPerformed(evt);
            }
        });

        Mes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Mes.setText("mes");
        Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesActionPerformed(evt);
            }
        });

        wa3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        wa3.setText("Registro de Tarjeta");

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        Año.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Año.setText("año");

        wa2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        wa2.setText("/");

        numeroTarjeta1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numeroTarjeta1.setText("****");
        numeroTarjeta1.setToolTipText("");
        numeroTarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjeta1ActionPerformed(evt);
            }
        });

        numeroTarjeta2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numeroTarjeta2.setText("****");
        numeroTarjeta2.setToolTipText("");
        numeroTarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjeta2ActionPerformed(evt);
            }
        });

        numeroTarjeta3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numeroTarjeta3.setText("****");
        numeroTarjeta3.setToolTipText("");
        numeroTarjeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjeta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(wa4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wa)
                            .addComponent(wa1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(wa2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(volver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 264, Short.MAX_VALUE)
                .addComponent(wa3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(wa3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wa4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wa1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wa2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjetaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        //hacer
    }//GEN-LAST:event_volverActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        if(numeroTarjeta.getText().equalsIgnoreCase("") ||  Mes.getText().equalsIgnoreCase("") ||  Año.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "Error, los campos deben estar llenos");

        }else{
            //inserta usuario en base de datos
            Tarjeta tarjeta= new Tarjeta(null,numeroTarjeta.getText()+numeroTarjeta1.getText()+numeroTarjeta2.getText()+numeroTarjeta3.getText(),Mes.getText()+"/"+Año.getText());
            BD load = new BD();

            try {
                load.conectaDefinitivo(us, null, tarjeta);
            } catch (SQLException ex) {
                Logger.getLogger(FormularioUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Se agrego la tarjeta con exito");

            //hacer
            this.dispose();
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesActionPerformed

    private void numeroTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjeta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjeta1ActionPerformed

    private void numeroTarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjeta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjeta2ActionPerformed

    private void numeroTarjeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjeta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjeta3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Año;
    private javax.swing.JTextField Mes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JTextField numeroTarjeta1;
    private javax.swing.JTextField numeroTarjeta2;
    private javax.swing.JTextField numeroTarjeta3;
    private javax.swing.JButton registrar;
    private javax.swing.JButton volver;
    private javax.swing.JLabel wa;
    private javax.swing.JLabel wa1;
    private javax.swing.JLabel wa2;
    private javax.swing.JLabel wa3;
    private javax.swing.JLabel wa4;
    // End of variables declaration//GEN-END:variables
}
