/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import BaseDdatos.BD;
import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Menu extends javax.swing.JFrame {

    Usuario usuario = null;
    List<Producto> listaProd;
    public static List <Producto> carritoProd=new ArrayList();
    public static int numeroFiltroTipo=0;
        
    public Menu() throws SQLException {
        iniciador();
    }
    
    public Menu(Usuario usuario) throws SQLException{
        this.usuario=usuario;
        iniciador();
    }
    
    public Menu(Usuario usuario, int num) throws SQLException{
        this.usuario=usuario;
        iniciador();
        carritoProd= new ArrayList();
        contadorItems.setText("Total items en el carrito: "+carritoProd.size());
    }
    
    public void iniciador() throws SQLException{
        initComponents();
        actualizaIconos(icono,"Logoletras.png",350,141);
        setLocationRelativeTo(null);
        actualizaProducto();
        generaLista(null,0);
        contadorItems.setText("Total items en el carrito: "+carritoProd.size());
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/LogoDgatito.png")));
    }
    
    public String textoUsuario(Usuario usuario){
        if (usuario == null)
        {
         return "Iniciar sesión";   
        }
        else
        {
         return ("Hola "+usuario.getNombre()+"!");
        }
    }
    
    public void seleccionarProducto(){
        productos.getSelectedIndex();
    }
    
    public void generaLista(String filtro,int filtroTipo) throws SQLException{
        listaProd= new ArrayList();
        
        BD load = new BD();
        
        load.conectaListaProductos(listaProd,filtro,filtroTipo);
        
        String[] listado =new String[listaProd.size()];
        
        for(int i=0;i<listaProd.size();i++){
            listado[i]=listaProd.get(i).cadenaProducto();
        }
        productos.setListData(listado);
        
    }
    
    public void actualizaProducto(){
        List<String> lista;
        lista = new ArrayList();
        lista.add("hola");
        lista.add("jaja");
        
        String[] vector= new String[lista.size()];
        for(int i=0; i<lista.size(); i++){
            vector[i]=lista.get(i);
        }
        productos.setListData(vector);
    }
    
    public void ClickUsuario(Usuario us){
        if(us==null){
            InicioSesion ini = new InicioSesion();
            ini.setVisible(true);
            this.dispose();
        }else{
            MenuUsuario submenu = new MenuUsuario(us);
            submenu.setVisible(true);
            this.dispose();
        }
    }
    
    private void actualizaIconos(JLabel icono, String nombre,int ancho,int alto){
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/"+nombre));
        icono.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        IconoUsuario = new javax.swing.JLabel();
        IconoCarrito = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JList<>();
        botonAgregarCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaFiltro = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        contadorItems = new javax.swing.JLabel();
        botonTodo = new javax.swing.JRadioButton();
        botonRopa = new javax.swing.JRadioButton();
        BotonAccesorios = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda elGatito");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 1000));

        jPanel1.setBackground(new java.awt.Color(241, 118, 3));

        IconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        IconoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoUsuarioMouseClicked(evt);
            }
        });

        IconoCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito2.png"))); // NOI18N
        IconoCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconoCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoCarritoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(textoUsuario(usuario));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carrito");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(IconoUsuario)
                        .addGap(69, 69, 69)))
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoCarrito)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconoCarrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(241, 118, 3));

        productos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        productos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(productos);

        botonAgregarCarrito.setText("Añadir a carrito");
        botonAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCarritoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("Buscar por nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel4.setText("Productos");

        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });

        contadorItems.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        contadorItems.setText("Total de items en el carrito: 0");

        filtroTipo.add(botonTodo);
        botonTodo.setSelected(true);
        botonTodo.setText("Todo");
        botonTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTodoActionPerformed(evt);
            }
        });

        filtroTipo.add(botonRopa);
        botonRopa.setText("Ropa");
        botonRopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRopaActionPerformed(evt);
            }
        });

        filtroTipo.add(BotonAccesorios);
        BotonAccesorios.setText("Accesorios");
        BotonAccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoriosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel5.setText("Filtrar por tipo: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contadorItems)
                                    .addComponent(botonAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(botonTodo)
                                    .addGap(46, 46, 46)
                                    .addComponent(botonRopa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonAccesorios))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(cajaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(buscar))))
                        .addContainerGap(68, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cajaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTodo)
                    .addComponent(botonRopa)
                    .addComponent(BotonAccesorios))
                .addGap(67, 67, 67)
                .addComponent(botonAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(contadorItems)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoUsuarioMouseClicked
        // TODO add your handling code here:
        ClickUsuario(usuario);
        
    }//GEN-LAST:event_IconoUsuarioMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ClickUsuario(usuario);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void botonAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCarritoActionPerformed
        // TODO add your handling code here:
        int lugarItem=productos.getSelectedIndex();
        if(carritoProd.size()>=0 && carritoProd.size()<15 && lugarItem>=0)
        {
            carritoProd.add(listaProd.get(lugarItem));
            System.out.print("carritoProdsize:"+carritoProd.size());
            
        }else{
            JOptionPane.showMessageDialog(null, "Solo se permite hasta 15 productos por pedido\n Disculpe las molestias");
        }
        contadorItems.setText("Total items en el carrito: "+(carritoProd.size()));
        
    }//GEN-LAST:event_botonAgregarCarritoActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        try {
            generaLista(cajaFiltro.getText(),numeroFiltroTipo);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarMouseClicked

    private void BotonAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoriosActionPerformed
        numeroFiltroTipo=2;
        try {
            generaLista(cajaFiltro.getText(),numeroFiltroTipo);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonAccesoriosActionPerformed

    private void botonRopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRopaActionPerformed
         numeroFiltroTipo=1;
         try {
            generaLista(cajaFiltro.getText(),numeroFiltroTipo);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonRopaActionPerformed

    private void botonTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTodoActionPerformed
         numeroFiltroTipo=0;
         try {
            generaLista(cajaFiltro.getText(),numeroFiltroTipo);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonTodoActionPerformed

    private void IconoCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoCarritoMouseClicked
        // TODO add your handling code here:
        if(usuario!=null && !carritoProd.isEmpty()){
   
        Menucarrito ventana =new Menucarrito(usuario,carritoProd);
        ventana.setVisible(true);
        this.dispose();
        }else{
            
            JOptionPane.showMessageDialog(null, "error, se necesita iniciar sesion y agregar al menos 1 producto para continuar");
        }
    }//GEN-LAST:event_IconoCarritoMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonAccesorios;
    private javax.swing.JLabel IconoCarrito;
    private javax.swing.JLabel IconoUsuario;
    private javax.swing.JButton botonAgregarCarrito;
    private javax.swing.JRadioButton botonRopa;
    private javax.swing.JRadioButton botonTodo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cajaFiltro;
    private javax.swing.JLabel contadorItems;
    private javax.swing.ButtonGroup filtroTipo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> productos;
    // End of variables declaration//GEN-END:variables
}
